// @vitest-environment node
import { randomUUID } from "node:crypto";
import { expect, it, vi } from "vitest";
import sharp from "sharp";
import type { PrismaClient } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { processNextImageJob, recoverImageJobs } from "./image-worker";
import { queueArticleImage } from "./image-jobs";

async function scenario(run: (client: PrismaClient, userId: string, jobId: string) => Promise<void>) {
  vi.stubEnv("GEMINI_API_KEY", "test-key");
  for (const key of ["CLOUDFLARE_R2_ACCOUNT_ID", "CLOUDFLARE_R2_BUCKET", "CLOUDFLARE_R2_ACCESS_KEY_ID", "CLOUDFLARE_R2_SECRET_ACCESS_KEY"]) vi.stubEnv(key, "test");
  vi.stubEnv("R2_PUBLIC_BASE_URL", "https://images.example.com");
  const rollback = new Error("rollback fixtures");
  try {
    await prisma.$transaction(async tx => {
      await tx.lLMModelPrice.create({ data: { provider: "gemini", model: "gemini-3.1-flash-image", inputUsdPerMillionTokens: "0.50", outputUsdPerMillionTokens: "3", imageOutputUsdPerMillionTokens: "60", effectiveAt: new Date(Date.now() - 1) } });
      const user = await tx.user.create({ data: { username: `image-${randomUUID()}`, displayName: "Image test", passwordHash: "test", mustChangePassword: false } });
      const job = await tx.imageGeneration.create({ data: { userId: user.id, locale: "zh-tw", title: "AI 教學", paragraphs: [{ id: "p1", tag: "p", text: "建立公開品牌資料" }], targetId: "p1", prompt: "A brand illustration", alt: "品牌插畫", reason: "協助理解", model: "gemini-3.1-flash-image", imageSize: "512", aspectRatio: "9:16", altModel: "gemini-3.1-flash-lite" } });
      await run(tx as unknown as PrismaClient, user.id, job.id);
      throw rollback;
    }, { timeout: 15000 });
  } catch (e) { if (e !== rollback) throw e; }
  finally { vi.unstubAllEnvs(); }
}
const usage = { inputTokens: 10, outputTokens: 747, totalTokens: 757, imageOutputTokens: 747 };
const queue = (client: PrismaClient, user: string, id: string) => queueArticleImage(client, user, id, { action: "generate", prompt: "A brand illustration", alt: "品牌插畫", targetId: "p1" });

it("queues once, preserves generated bytes through upload failure, and retries upload without another generation", () => scenario(async (client, user, id) => {
  await Promise.all([queue(client, user, id), queue(client, user, id)]);
  const bytes = await sharp({ create: { width: 16, height: 32, channels: 3, background: "blue" } }).png().toBuffer();
  const generate = vi.fn(async () => ({ bytes, mimeType: "image/png", usage }));
  const upload = vi.fn().mockRejectedValueOnce(new Error("R2 offline")).mockResolvedValue("https://images.example.com/image.webp");
  await processNextImageJob(client, { generate, upload });
  expect((await client.imageGeneration.findUniqueOrThrow({ where: { id } })).status).toBe("GENERATED");
  await processNextImageJob(client, { generate, upload });
  const failed = await client.imageGeneration.findUniqueOrThrow({ where: { id } });
  expect(failed.status).toBe("FAILED"); expect(failed.imageBytes?.byteLength).toBe(bytes.length);
  await queueArticleImage(client, user, id, { action: "retry-upload" });
  await processNextImageJob(client, { generate, upload });
  const ready = await client.imageGeneration.findUniqueOrThrow({ where: { id } });
  expect(ready).toMatchObject({ status: "READY", width: 16, height: 32, alt: "品牌插畫", imageBytes: null });
  expect(generate).toHaveBeenCalledTimes(1);
  expect(await client.lLMUsage.findFirst({ where: { promptDefinition: { key: "IMAGE_ALT" } } })).toBeNull();
  expect(upload).toHaveBeenCalledTimes(2);
  expect(await processNextImageJob(client, { generate, upload })).toBe(false);
  const audit = await client.lLMUsage.findFirst({ where: { promptDefinition: { key: "IMAGE_GENERATE" } }, orderBy: { createdAt: "desc" } });
  expect(audit?.imageOutputTokens).toBe(747);
  expect(audit?.estimatedCostUsd?.toNumber()).toBeCloseTo(0.044825, 8);
}));

it("does not replay unknown generation and refuses jobs owned by another user", () => scenario(async (client, user, id) => {
  await expect(queue(client, "other-user", id)).rejects.toThrow("找不到");
  await queue(client, user, id);
  const generate = vi.fn(async () => { throw Object.assign(new Error("timeout"), { generationStatusUnknown: true }); });
  await processNextImageJob(client, { generate });
  expect((await client.imageGeneration.findUniqueOrThrow({ where: { id } })).status).toBe("UNKNOWN");
  await queue(client, user, id);
  expect(await processNextImageJob(client, { generate })).toBe(false);
  expect(generate).toHaveBeenCalledTimes(1);
  await expect(queueArticleImage(client, user, id, { action: "retry-upload" })).rejects.toThrow("尚無");
}));

it("recovers expired upload leases but marks interrupted generations unknown", () => scenario(async (client, _user, id) => {
  await client.imageGeneration.update({ where: { id }, data: { status: "GENERATING", leaseExpiresAt: new Date(0) } });
  await recoverImageJobs(client);
  expect((await client.imageGeneration.findUniqueOrThrow({ where: { id } })).status).toBe("UNKNOWN");
  await client.imageGeneration.update({ where: { id }, data: { status: "UPLOADING", imageBytes: new Uint8Array([1]), leaseExpiresAt: new Date(0) } });
  await recoverImageJobs(client);
  expect((await client.imageGeneration.findUniqueOrThrow({ where: { id } })).status).toBe("GENERATED");
}));
